version: "3.9"
services:
    main-service:
        image: fiftysix/bitcoin-core:latest
        container_name: bitcoin-core-testnet
        command: bitcoind --testnet --server=1 --rpcbind=0.0.0.0 --rpcport=18332 --rpcallowip=0.0.0.0/0
        ports:
            - 18332:18332
            - 18333:18333
        volumes:
            - bitcoin-core-testnet-data:/node/bitcoin-core
        networks:
            - bitcoin-testnet-net
networks:
    bitcoin-testnet-net:
        driver: bridge
volumes:
    bitcoin-core-testnet-data:
        labels:
            blockchain.software: bitcoin-core
