services:
  bitcoin-core:
    image: fiftysix/bitcoin-core:latest
    container_name: bitcoin-core
    command: bitcoind ${FIFTYSIX_BITCOIN_EXTRA_ARGS}
    ports:
      - "${FIFTYSIX_BITCOIN_RPC_PORT:-8332}:${FIFTYSIX_BITCOIN_RPC_PORT:-8332}"
      - "8333:8333"
    volumes:
      - "${FIFTYSIX_BITCOIN_STORAGE_PATH:-bitcoin-core-data}:/node/bitcoin-core"
    networks:
      - bitcoin-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: ${FIFTYSIX_BITCOIN_LIMITS_CPUS:-}
          memory: ${FIFTYSIX_BITCOIN_LIMITS_MEMORY:-}
        reservations:
          cpus: ${FIFTYSIX_BITCOIN_RESERVATIONS_CPUS:-}
          memory: ${FIFTYSIX_BITCOIN_RESERVATIONS_MEMORY:-}

networks:
  bitcoin-net:
    driver: bridge

volumes:
  bitcoin-core-data:
    labels:
      - "blockchain.software=bitcoin-core"
