services:
  bitcoin-core:
    image: fiftysix/bitcoin-core:latest
    container_name: bitcoin-core
    command: bitcoind ${BITCOIN_EXTRA_ARGS}
    ports:
      - "${FIFTYSIX_BITCOIN_RPC_PORT:-8332}:${FIFTYSIX_BITCOIN_RPC_PORT:-8332}"
      - "8333:8333"
    volumes:
      - bitcoin-core-data:/node/bitcoin-core
    networks:
      - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge

volumes:
  bitcoin-core-data:
    labels:
      - "blockchain.software=bitcoin-core"
